# Generated by Django 4.0 on 2022-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieURL',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('tmdbId', models.IntegerField()),
                ('movie_url', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
